---
- name: "Configure cri-o registries"
  template:
    src: registries.conf.j2
    dest: /etc/containers/registries.conf
    mode: 0755
  notify: restart crio

- name: "Configure storage"
  ini_file:
    dest: '/etc/containers/storage.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '"{{ item.value }}"'
    mode: 0644
  with_items: "{{ crio_storage }}"
  notify: restart crio

- name: "Configure cri-o"
  ini_file:
    dest: '/etc/crio/crio.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '"{{ item.value }}"'
    mode: 0644
  with_items: "{{ crio_config }}"
  notify: restart crio
