apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: ingress-system
spec:
  url: https://metallb.github.io/metallb
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: ingress-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: ingress-system
      interval: 1m
  values:
    speaker:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    controller:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 172.17.13.100-172.17.13.150
#    prometheus:
#      podMonitor:
#        enabled: true
#      prometheusRule:
#        enabled: true
