apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1m
  path: ./k8s-manifest-gitops/flux/07_ingress/cert-manager-issuer.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
