apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: "https://helm.cilium.io/"
  chart: cilium
  targetNamespace: kube-system
  valuesContent: |-
    # Set kubeProxyReplacement to "strict" in order to prevent CVE-2020-8554 and fully remove kube-proxy.
    # See https://cilium.io/blog/2020/12/11/kube-proxy-free-cve-mitigation for more information.
    kubeProxyReplacement: "strict"
    k8sServiceHost: 10.0.2.15
    k8sServicePort: 6443
    global:
      encryption:
        enabled: true
        nodeEncryption: true
    hubble:
      metrics:
        #serviceMonitor:
        #  enabled: true
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
      ui:
        enabled: true
        replicas: 1
        ingress:
          enabled: true
          hosts:
            - hubble.k8s.intra
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          tls:
          - secretName: letsencrypt-hubble-ui
            hosts:
            - hubble.k8s.intra
      relay:
        enabled: true
    operator:
      replicas: 1
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDR: "10.43.0.0/16"
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDR: "fd00::/104"
        clusterPoolIPv6MaskSize: 120
    prometheus:
      enabled: true
      # Default port value (9090) needs to be changed since the RHEL cockpit also listens on this port.
      port: 19090
      # Configure this serviceMonitor section AFTER Rancher Monitoring is enabled!
      #serviceMonitor:
      #  enabled: true
