piVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: ingress-system
spec:
  url: https://charts.jetstack.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: ingress-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: ingress-system
      interval: 1m
  values:
    installCRDs: true
    clusterResourceNamespace: "ingress-system"
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
    prometheus:
      enabled: true
#      servicemonitor:
#        enabled: true
#        namespace: "ingress-system"
