---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - identity: {}
    - aesgcm:
        keys:
        - name: key1
          secret: CYB2Rnqcz8XNKGHmmPD2YS9HGcx0NTakwJN/wsWZ2aQ=
