---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kyverno-policy-reporter
  namespace: kyverno-system
spec:
  chart: policy-reporter
  repo: "https://kyverno.github.io/policy-reporter"
  targetNamespace: kyverno-system
  valuesContent: |-
    # enable policy-report-ui
    ui:
      enabled: true
      plugins:
        kyverno: true
    kyvernoPlugin:
      enabled: true
    monitoring:
      enabled: false
      namespace: cattle-dashboards
    # Supported targets for new PolicyReport Results
    plugins.kyverno=true
    target:
      loki:
        # loki host address
        host: ""
        # minimum priority "" < info < warning < critical < error
        minimumPriority: ""
        # Skip already existing PolicyReportResults on startup
        skipExistingOnStartup: true
      ui:
        # teams webhook address
        host: "kyverno.k8s.intra"
        # minimum priority "" < info < warning < critical < error
        minimumPriority: "info"
        # Skip already existing PolicyReportResults on startup
        skipExistingOnStartup: true
