apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keycloak
  namespace: keycloak
spec:
  repo: "https://codecentric.github.io/helm-charts"
  chart: keycloak
  targetNamespace: keycloak
  valuesContent: |-
    rbac:
      create: true
    extraEnv: |
      - name: KEYCLOAK_USER
        value: "admin"
      - name: KEYCLOAK_PASSWORD
        value: "password"
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_HTTP_PORT
        value: "80"
      - name: KEYCLOAK_HTTPS_PORT
        value: "443"
      - name: KEYCLOAK_HOSTNAME
        value: keycloak.k8s.intra
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://keycloak.k8s.intra/auth/"
      - name: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - name: WILDFLY_LOGLEVEL
        value: DEBUG
      - name: CACHE_OWNERS_COUNT
        value: "2"
      - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
        value: "2"
    ingress:
      enabled: true
      servicePort: http
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: ca-issuer
      rules:
        -
          host: 'keycloak.k8s.intra'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - keycloak.k8s.intra
          secretName: "keycloak-inress-tls"
