---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pushprox-kube-scheduler
  namespace: monitoring-system
spec:
  chart: PushProx
  repo: "https://devopstales.github.io/helm-charts"
  targetNamespace: monitoring-system
  valuesContent: |-
    metricsPort: 10259
    component: kube-scheduler
    clients:
      port: 10012
      useLocalhost: true
      https:
        enabled: true
        useServiceAccountCredentials: true
        insecureSkipVerify: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"